FROM golang:1.17-alpine AS builder

WORKDIR /temp
COPY . /temp

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o executable cmd/consumer/main.go

FROM scratch

#RUN apk --no-cache add ca-certificates

WORKDIR /consumer
COPY --from=builder /temp/executable .

CMD [ "/consumer/executable",  "-brokers", "broker:9092", "-topics", "coordinates", "-group", "g1"]