apiVersion: v1
kind: Pod
metadata:
  name: server-tag-1
spec:
  containers:
  - name: server-app
    image: europe-north1-docker.pkg.dev/reference-yen-341621/dockers/eventrecord-server:1.0.0
  - name: zookeeper-app
    image: europe-north1-docker.pkg.dev/reference-yen-341621/dockers/wurstmeister/zookeeper:latest
    ports:
      - containerPort: 80
  - name: kafka-app
    image: europe-north1-docker.pkg.dev/reference-yen-341621/dockers/wurstmeister/kafka:latest
    env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_CREATE_TOPICS
      value: "coordinates:4:1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_LISTENERS
      value: "INTERNAL://broker:9092,EXTERNAL://localhost:9093"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "INTERNAL://broker:9092,EXTERNAL://localhost:9093"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "INTERNAL"